angel/urls.py
from django.urls import path

from angel import views

app_name = 'angel'

urlpatterns = [
    path('', views.home, name='home'),
    path('angel/search/', views.search, name='search'),
    path('angel/category/<int:category_id>/',
         views.category, name='category'),
    path('angel/<int:id>/', views.piece, name='piece'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('angel.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

angel/models.py
from brand.models import Brand
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Clothes(models.Model):
    class Meta:
        verbose_name = 'Roupa'
        verbose_name_plural = 'Roupas'
        ordering = ('-created_at',)

    GENDER_CHOICES = (
        ('Feminino', 'Feminino'),
        ('Masculino', 'Masculino'),
        ('Unisex', 'Unisex')
    )
    title = models.CharField('Título', max_length=65)
    description = models.TextField('Descrição')
    gender = models.CharField(
        'Gênero', max_length=9, choices=GENDER_CHOICES,
        blank=False, null=False, default='Unisex')
    length = models.CharField('Tamanho', max_length=100)
    value = models.DecimalField(
        'Valor', max_digits=6, decimal_places=2, default=0.00)
    qty_parcel = models.IntegerField(
        'Quantidade de Parcelas', null=True, blank=True)
    value_parcel = models.DecimalField(
        'Valor das Parcelas', max_digits=6, decimal_places=2,
        default=0.00, null=True, blank=True)
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizaco em', auto_now=True)
    is_published = models.BooleanField('Está publicado', default=False)
    cover = models.ImageField(
        'Imagem', upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, verbose_name='Categoria', on_delete=models.SET_NULL,
        null=True, blank=True, default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, verbose_name='Autor', null=True
    )
    brands = models.ManyToManyField(Brand, verbose_name='Marca')

    def __str__(self):
        return self.title

brand/models.py
import string
from random import SystemRandom

from django.db import models
from django.utils.text import slugify


class Brand(models.Model):
    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    brand = models.CharField(max_length=30)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            rand_letters = ''.join(
                SystemRandom().choices(
                    string.ascii_letters + string.digits,
                    k=5,
                )
            )
            self.slug = slugify(f'{self.brand}-{rand_letters}')
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.brand

angel/views.py
from decouple import config
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from utils.pagination import make_pagination

from angel.models import Clothes

PER_PAGES = config('PER_PAGES')


def home(request):
    clothes = Clothes.objects.filter(
        is_published=True,).order_by('-id')

    page_obj, pagination_range = make_pagination(request, clothes, PER_PAGES)

    return render(request, 'angel/pages/home.html', context={
        'clothes': page_obj,
        'pagination_range': pagination_range,
    })


def category(request, category_id):
    clothes = get_list_or_404(Clothes.objects.filter(
        category__id=category_id, is_published=True,).order_by('-id'))

    page_obj, pagination_range = make_pagination(request, clothes, PER_PAGES)

    return render(request, 'angel/pages/category.html', context={
        'clothes': page_obj,
        'pagination_range': pagination_range,
        'title': f'Categoria-{clothes[0].category.name}'
    })


def piece(request, id):
    clothe = get_object_or_404(Clothes, pk=id, is_published=True)

    return render(request, 'angel/pages/piece-view.html', context={
        'clothe': clothe,
        'is_detail_page': True,
    })


def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    clothes = Clothes.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term) |
            Q(gender__icontains=search_term) |
            Q(slug__icontains=search_term),
        ), is_published=True
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, clothes, PER_PAGES)

    return render(request, 'angel/pages/search.html', {
        'page_title': f'Pesquisa por "{search_term}" |',
        'search_term': search_term,
        'clothes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}',
    })

brand/views.py
from django.shortcuts import render

# Create your views here.

angel/templates/angel/pages/category.html
{% extends 'global/base.html' %}

{% block title %} {{ title }} | {% endblock title %} 

{% block content %}
<div class="main-content main-content-list container">
    {% for clothe in clothes %}
        {% include 'angel/partials/piece.html' %}
    {% endfor %}
</div>
{% endblock content %}

angel/templates/angel/pages/gender.html
{% extends 'global/base.html' %}

{% block title %} {{ title }} | {% endblock title %} 

{% block content %}
<div class="main-content main-content-list container">
    {% for clothe in clothes %}
        {% include 'angel/partials/piece.html' %}
    {% endfor %}
</div>
{% endblock content %}

angel/templates/angel/pages/home.html
{% extends 'global/base.html' %}

{% block title %} Início | {% endblock title %} 

{% block content %}
<div class="main-content main-content-list container">
    {% for clothe in clothes %}
        {% include 'angel/partials/piece.html' %}
    {% empty %}
        <div class="margin">
            <h1>Não achamos nada aqui 😭</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}

angel/templates/angel/pages/piece-view.html
{% extends 'global/base.html' %}

{% block title %} {{ clothes.title }} | {% endblock title %}  

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'angel/partials/piece.html' %}
</div>
{% endblock content %}

angel/templates/angel/pages/search.html
{% extends 'global/base.html' %}

{% block title %} {{ page_title }} {% endblock title %} 

{% block content %}
<div class="main-content main-content-list container">
    {% for clothe in clothes %}
        {% include 'angel/partials/piece.html' %}
    {% empty %}
        <div class="margin">
            <h1>Não achamos nada referente a está pesquisa: {{search_term}} 😭</h1>     
            <a class="back" href="{% url 'angel:home' %}"><i class="fas fa-backward"></i> Voltar</a>
        </div>
    {% endfor %}
</div>

{% endblock content %}

angel/templates/angel/partials/footer.html
<footer class="main-footer">
    <div>
        <h2>Localização</h2>
        <address>Cidade- Eldorado<br>CEP- 79970-000<br>Rua- Santa Terezinha n°507, centro</address>
        <a href="https://www.google.com.br/maps/place/R.+Santa+Teresinha,+499+-+Centro,+Eldorado+-+MS,+79970-000/@-23.7900533,-54.2819831,21z/data=!4m5!3m4!1s0x948b4f9327a6e98b:0xe0512cc7546de66f!8m2!3d-23.7901081!4d-54.2819963?hl=pt-BR&authuser=0" target="_blank" rel="noreferrer noopener"><i
        class="fas fa-store "></i> Ver no mapa</a>
    </div>

    <div class="padding">
        <h2>Siga-nos</h2>
        <a href="https://www.instagram.com/loja_angeel/" target="_blank" rel="noreferrer noopener"><i
                class="fab fa-instagram"></i> Loja Angel</a>
    </div>

    <div class="padding">
        <h2>Entre em contato</h2>
        <a href="https://wa.me/5567981234634" target="_blank" rel="noreferrer noopener"><i class="fab fa-whatsapp"></i>
            Whatsapp</a><br>
        <a href="https://www.instagram.com/direct/t/340282366841710300949128398897259383253" target="_blank"
            rel="noreferrer noopener"><i class="fab fa-instagram"></i>
            Direct</a>
    </div>
</footer>

angel/templates/angel/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'global/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'global/css/style.css' %}">

angel/templates/angel/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'angel:home' %}">
                <span class="main-logo-text">Angel Moda Infantil</span>
            </a>
        </h1>
    </div>
</header>

angel/templates/angel/partials/pagination.html
{% if clothes.has_other_pages %}
    <nav role="navigation" aria-label="Main Pagination" class="container pagination">
        <div class="pagination-content">

            {% if pagination_range.first_page_out_of_range %}
                <a class="page-link page-item" aria-label="Go to page 1" href="?page=1{{ additional_url_query }}">1</a>
                <span class="page-item">...</span>
            {% endif %}

            {% for page in pagination_range.pagination %}
                {% if pagination_range.current_page == page %}
                <a class="page-link page-item page-current" aria-label="Current page, {{ page }}" aria-current="true" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                {% else %}
                    <a class="page-link page-item" aria-label="Go to page {{ page }}" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                {% endif %}
            {% endfor %}

            {% if pagination_range.last_page_out_of_range %}
            <span class="page-item">...</span>
                <a class="page-link page-item" aria-label="Go to page {{ pagination_range.total_pages }}" href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}">{{ pagination_range.total_pages }}</a>
            {% endif %}

        </div>
    </nav>
{% endif %}

angel/templates/angel/partials/piece.html
<div class="recipe recipe-list-item">
    {% if clothe.cover.url is not Null %}
        <div class="recipe-cover">
            <a href="{% url 'angel:piece' clothe.id %}">
                <img src="{{ clothe.cover.url }}" alt="" />
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'angel:piece' clothe.id %}">
                {{ clothe.title }}
            </a>
        </h2>
        <div class="recipe-author-item">
            <span class="recipe-author-item">
                <i class="fas fa-calendar-alt"></i>
                {{clothe.created_at|date:"d/m/Y" }} às {{ clothe.created_at|date:"H:i" }}
            </span>

            {% if clothe.category is not None %}
                <span class="recipe-author-item">
                    <a href="{% url 'angel:category' clothe.category.id %}">
                        <i class="fas fa-socks"></i>
                        <span>{{ clothe.category.name }}</span>
                    </a>
                </span>
            {% endif %}
        </div>
    </div>
    
    <div class="recipe-value-container">
        <div class="recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fas fa-money-bill"></i> Valores
            </h3>
                <div class="recipe-meta-text">A vista: R${{ clothe.value }} ou</div>
                <div class="recipe-meta-text">Parcelado: {{ clothe.qty_parcel }}X de R${{ clothe.value_parcel }}</div>
        </div>
    </div>   

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fas fa-ruler"></i> Tamanhos disponíveis
            </h3>
            <div class="recipe-meta-text">{{ clothe.length }}</div> 
        </div>
    </div>   
    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'angel:piece' clothe.id %}">
                <i class="fas fa-eye"></i>
                <span>Veja mais...</span>
            </a>
        </footer>
    {% endif %}
    {% if is_detail_page is True %}
        <div class="recipe-content preparation-steps">
            <p>
                {{ clothe.description }} |
                {{ clothe.gender }}
            </p><br>
            <p>
                Se interessou?! Entre em contato!
            </p>
        </div>
        <a class="back" href="{% url 'angel:home' %}"><i class="fas fa-backward"></i> Voltar</a>
    {% endif %}

</div>

angel/templates/angel/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'angel:search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required placeholder="Encontre o que precisa aqui!">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>